# Generated by Django 6.0.6 on 2026-07-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Talha', max_length=100)),
                ('profile_picture', models.ImageField(upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
